Repository dotnet/blazor, pull requests merged in 2019-09, with the labels that each got.

#1894 Update to 5.0 SDK
  global.json
Labels: area-infrastructure

#1897 [release/3.0] Switch to embedded package icon
  Directory.Build.props
  global.json
  packageIcon.png
  src/Microsoft.AspNetCore.Blazor.Mono/Microsoft.AspNetCore.Blazor.Mono.csproj
  src/Microsoft.AspNetCore.Blazor.Mono/Microsoft.AspNetCore.Blazor.Mono.nuspec
Labels: area-infrastructure

#1903 Update branding to 3.1.0-preview2
  eng/Versions.props
Labels: area-platform, blocked

#1906 Update branding to 3.1.0-preview2
  eng/Versions.props
Labels: area-platform
